apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin-api.name" . }}
  namespace: {{ include "edge-dns.namespace" . }}
  labels:
    {{- include "edge-dns.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "admin-api.name" . }}
    app.kubernetes.io/part-of: edge-dns
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.admin-api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "admin-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
