apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clickhouse.name" . }}-data
  namespace: {{ include "edge-dns.namespace" . }}
  labels:
    {{- include "edge-dns.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/part-of: edge-dns
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.clickhouse.persistence.data.storageClass }}
  storageClassName: {{ .Values.clickhouse.persistence.data.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.clickhouse.persistence.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clickhouse.name" . }}-logs
  namespace: {{ include "edge-dns.namespace" . }}
  labels:
    {{- include "edge-dns.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/part-of: edge-dns
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.clickhouse.persistence.logs.storageClass }}
  storageClassName: {{ .Values.clickhouse.persistence.logs.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.clickhouse.persistence.logs.size }}
