apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.name" . }}
  namespace: {{ include "edge-dns.namespace" . }}
  labels:
    {{- include "edge-dns.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "redis.name" . }}
    app.kubernetes.io/part-of: edge-dns
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
