apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-data
  namespace: edge-dns
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: edge-dns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-logs
  namespace: edge-dns
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: edge-dns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
